* Colab jupyter notebook끼리 import하기 위한 선언

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/MyDrive/Colab Notebooks/밑바닥부터 시작하는 딥러닝 1

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import sys, os

In [3]:
sys.path.append('/content/drive/MyDrive/Colab Notebooks/밑바닥부터 시작하는 딥러닝 2/sample')

In [4]:
sys.path

['',
 '/content',
 '/env/python',
 '/usr/lib/python37.zip',
 '/usr/lib/python3.7',
 '/usr/lib/python3.7/lib-dynload',
 '/usr/local/lib/python3.7/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/local/lib/python3.7/dist-packages/IPython/extensions',
 '/root/.ipython',
 '/content/drive/MyDrive/Colab Notebooks/밑바닥부터 시작하는 딥러닝 2/sample']

### 신경망 복습

In [5]:
x = np.array([1,2,3])
print(x, x.shape)

[1 2 3] (3,)


In [6]:
y = np.array([[1],[2],[3]])
print(y, y.shape)

[[1]
 [2]
 [3]] (3, 1)


In [7]:
print(x.ndim, y.ndim)

1 2


In [8]:
W = np.array([[1,2,3], [4,5,6]])
X = np.array([[0,1,2], [3,4,5]])
W+X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [9]:
W = np.array([[1,2], [3,4]])
X = np.array([[5,6], [7,8]])
W+X

array([[ 6,  8],
       [10, 12]])

In [10]:
np.dot(W,X)

array([[19, 22],
       [43, 50]])

In [11]:
# 브로드 캐스트
A = np.array([[1,2], [3,4]])
A * 10

array([[10, 20],
       [30, 40]])

In [12]:
# 브로드 캐스트
A = np.array([[1,2], [3,4]])
B = np.array([10, 20])
A*B

array([[10, 40],
       [30, 80]])

### 신경망의 추론
- 학습
- 추론

In [13]:
W1 = np.random.randn(2,4) # 가중치
b1 = np.random.randn(4) # 편향
x =  np.random.randn(10, 2) # 입력 (미니배치, 입력)

In [14]:
h = np.matmul(x,W1) + b1

In [15]:
print(h)

[[ 1.24402889  1.29753034  1.30327267 -0.2520863 ]
 [ 2.0431557   0.76749928  1.48637986  0.58043654]
 [ 1.8354779   0.86011641  1.49076431  0.44736751]
 [ 1.51642623  0.996345    1.50447599  0.25411559]
 [ 2.99352357  0.83583621  0.89952069  0.28103813]
 [ 2.85861514  2.0818846  -0.46332954 -1.99406788]
 [ 2.83350961  1.04966572  0.73882764 -0.08443041]
 [ 3.06984031  1.75103878 -0.19525968 -1.42197148]
 [ 2.52448088  1.20313477  0.72732546 -0.31132872]
 [ 3.54210095  0.64496147  0.82601403  0.53329653]]


In [16]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [17]:
a = sigmoid(h)
print(a)

[[0.77626452 0.78541905 0.78638525 0.43731006]
 [0.88525421 0.68297969 0.81553429 0.64116785]
 [0.86241301 0.70268498 0.81619296 0.61001315]
 [0.82001162 0.73033936 0.81824111 0.56318923]
 [0.95228068 0.69758755 0.71085099 0.56980072]
 [0.94576231 0.88912995 0.38619626 0.11982717]
 [0.94445999 0.7407107  0.67673944 0.47890493]
 [0.9556314  0.85208377 0.45133959 0.1943527 ]
 [0.9258403  0.76908197 0.67421809 0.42279045]
 [0.97186222 0.65587414 0.69551146 0.63025165]]


In [18]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))


x =  np.random.randn(10, 2) # 입력 (미니배치, 입력)

W1 = np.random.randn(2,4) # 가중치 1
b1 = np.random.randn(4) # 편향 1

W2 = np.random.randn(4, 3) # 가중치 2
b2 = np.random.randn(3) # 편향 2

h = np.matmul(x, W1) + b1
a = sigmoid(h)
s = np.matmul(a, W2) + b2

print(s)

[[ 1.87292456 -2.04786593 -0.85410567]
 [ 1.45422298 -2.61264689 -1.49559446]
 [ 1.25208515 -2.36152796 -0.51238263]
 [ 1.75955797 -1.8897415  -0.0038938 ]
 [ 1.32038648 -2.60450206 -0.97674086]
 [ 0.88039477 -3.03201729 -1.00185015]
 [ 1.16056003 -2.24824958 -0.19545806]
 [ 1.33614451 -2.68176414 -1.54953833]
 [ 1.53130353 -2.5389411  -1.42468572]
 [ 1.50040572 -2.23105113 -0.62857145]]


In [19]:
class Sigmoid:
  def __init__(self):
    self.params = []

  def forward(self, x):
    return 1 / (1+ np.exp(-x))

In [20]:
class Affine:
  def __init__(self, W, b):
    self.params = [W,b]
  
  def forward(self, x):
    W, b = self.params
    out = np.matmul(x,W) + b
    return out

In [21]:
class TwoLayerNet:
  def __init__(self, input_size, hidden_size, output_size):
    I, H, O = input_size, hidden_size, output_size

    W1 = np.random.randn(I, H)
    b1 = np.random.randn(H)
    W2 = np.random.randn(H, O)
    b2 = np.random.randn(O)

    self.layers = [
                  Affine(W1, b1),
                  Sigmoid(),
                  Affine(W2, b2)
                ]

    self.params = []
    for layer in self.layers:
      self.params += layer.params
    
  def predict(self, x):
    for layer in self.layers:
      x = layer.forward(x)
    
    return x

In [22]:
x = np.random.randn(10,2)
model = TwoLayerNet(2,4,3)
model.predict(x)

array([[ 1.72826041,  1.50876335, -0.85571269],
       [ 1.76807542,  1.25612297, -1.19654371],
       [ 2.47426136,  1.80721698, -1.49138583],
       [ 2.26878054,  1.77239935, -1.16737545],
       [ 1.82667247,  1.57148806, -0.89766372],
       [ 2.02973031,  1.45790463, -1.32772142],
       [ 1.86704537,  1.33384528, -1.24435834],
       [ 2.00618541,  1.70209653, -0.61567572],
       [ 1.47919943,  1.54705152, -0.41597454],
       [ 2.063559  ,  1.7188641 , -0.94996465]])

### Repeat 노드

In [24]:
D, N = 8, 7
x = np.random.randn(1, D)
y = np.repeat(x, N, axis=0)
print(y)

[[-0.66320337 -1.15054689 -0.30074498 -0.9077794   0.93704086  1.4443923
  -1.16937584  0.97482053]
 [-0.66320337 -1.15054689 -0.30074498 -0.9077794   0.93704086  1.4443923
  -1.16937584  0.97482053]
 [-0.66320337 -1.15054689 -0.30074498 -0.9077794   0.93704086  1.4443923
  -1.16937584  0.97482053]
 [-0.66320337 -1.15054689 -0.30074498 -0.9077794   0.93704086  1.4443923
  -1.16937584  0.97482053]
 [-0.66320337 -1.15054689 -0.30074498 -0.9077794   0.93704086  1.4443923
  -1.16937584  0.97482053]
 [-0.66320337 -1.15054689 -0.30074498 -0.9077794   0.93704086  1.4443923
  -1.16937584  0.97482053]
 [-0.66320337 -1.15054689 -0.30074498 -0.9077794   0.93704086  1.4443923
  -1.16937584  0.97482053]]


In [26]:
dy = np.random.randn(N, D)
dx = np.sum(dy, axis=0, keepdims=True)
print(dx)

[[-4.69138242  2.53430626 -3.63224634 -3.16419435  1.81588964  3.00238837
   5.17004429 -0.52057372]]


### Sum 노드

In [28]:
D, N = 8,7
x = np.random.randn(N,D)
y = np.sum(x, axis=0, keepdims=True)
print(y)

[[ 1.93149787 -3.98249737  1.0200436   3.72716777  0.21304434  0.78117886
  -3.76913096 -2.66351462]]


In [30]:
dy = np.random.randn(1,D)
dx = np.repeat(dy, N, axis=0)
print(dx)

[[0.27165729 1.20266995 0.34746392 2.29133283 0.936639   0.70625469
  0.28537696 1.73339544]
 [0.27165729 1.20266995 0.34746392 2.29133283 0.936639   0.70625469
  0.28537696 1.73339544]
 [0.27165729 1.20266995 0.34746392 2.29133283 0.936639   0.70625469
  0.28537696 1.73339544]
 [0.27165729 1.20266995 0.34746392 2.29133283 0.936639   0.70625469
  0.28537696 1.73339544]
 [0.27165729 1.20266995 0.34746392 2.29133283 0.936639   0.70625469
  0.28537696 1.73339544]
 [0.27165729 1.20266995 0.34746392 2.29133283 0.936639   0.70625469
  0.28537696 1.73339544]
 [0.27165729 1.20266995 0.34746392 2.29133283 0.936639   0.70625469
  0.28537696 1.73339544]]


### MatMul 노드

In [31]:
class MatMul:
  def __init__(self, W):
    self.params = [W]
    self.grads = [np.zero_like(W)]
    self.x = None
  
  def forward(self, x):
    W, = self.params
    print(self.params)
    out = np.matmul(x,W)
    self.x = x
    return out

  def backward(self, dout):
    W, = self.params
    dx = np.matmul(dout, W.T)
    dW = np.matmul(self.x.T, dout)
    self.grads[0][...] = dW
    return dx

In [34]:
class Sigmoid:
  def __init__(self):
    self.params = []

  def forward(self, x):
    return 1 / (1+ np.exp(-x))

  def backward(self, dout):
    dx = dout * (1.0 - self.out) * self.out
    return dx

In [ ]:
class Affine:
  def __init__(self, W, b):
    self.params = [W,b]
    self.grads = [np.zeros_like(W), np.zeros_like(b)]
    self.x = None

  def forward(self, x):
    W,b = self.params
    out = np.matmul(x, W) + b
    return out
  
  def backward(self, dout):
    W,b = self.params
    dx = np.matmul(dout, W.T)
    dW = np.matmul(self.x.T, dout)
    db = np.sum(dout, axis=0)

    self.grads[0][...] = dW
    self.grads[1][...] = db

    return dx