* Colab jupyter notebook끼리 import하기 위한 선언

In [1]:
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/MyDrive/Colab Notebooks/밑바닥부터 시작하는 딥러닝 2

Mounted at /content/drive
/content/drive/MyDrive/Colab Notebooks/밑바닥부터 시작하는 딥러닝 2


In [2]:
import numpy as np
import matplotlib.pyplot as plt
import sys, os

In [3]:
sys.path.append('/content/drive/MyDrive/Colab Notebooks/밑바닥부터 시작하는 딥러닝 2/sample')

In [4]:
sys.path

['',
 '/content',
 '/env/python',
 '/usr/lib/python37.zip',
 '/usr/lib/python3.7',
 '/usr/lib/python3.7/lib-dynload',
 '/usr/local/lib/python3.7/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/local/lib/python3.7/dist-packages/IPython/extensions',
 '/root/.ipython',
 '/content/drive/MyDrive/Colab Notebooks/밑바닥부터 시작하는 딥러닝 2/sample']

### 신경망 복습

In [5]:
x = np.array([1,2,3])
print(x, x.shape)

[1 2 3] (3,)


In [6]:
y = np.array([[1],[2],[3]])
print(y, y.shape)

[[1]
 [2]
 [3]] (3, 1)


In [7]:
print(x.ndim, y.ndim)

1 2


In [8]:
W = np.array([[1,2,3], [4,5,6]])
X = np.array([[0,1,2], [3,4,5]])
W+X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [9]:
W = np.array([[1,2], [3,4]])
X = np.array([[5,6], [7,8]])
W+X

array([[ 6,  8],
       [10, 12]])

In [10]:
np.dot(W,X)

array([[19, 22],
       [43, 50]])

In [11]:
# 브로드 캐스트
A = np.array([[1,2], [3,4]])
A * 10

array([[10, 20],
       [30, 40]])

In [12]:
# 브로드 캐스트
A = np.array([[1,2], [3,4]])
B = np.array([10, 20])
A*B

array([[10, 40],
       [30, 80]])

### 신경망의 추론
- 학습
- 추론

In [13]:
W1 = np.random.randn(2,4) # 가중치
b1 = np.random.randn(4) # 편향
x =  np.random.randn(10, 2) # 입력 (미니배치, 입력)

In [14]:
h = np.matmul(x,W1) + b1

In [15]:
print(h)

[[-5.11473716e-01 -2.20584355e+00  1.32720694e-01  3.06201340e+00]
 [ 3.15386901e-03 -2.55377944e-02  5.60302764e-02  3.28144529e+00]
 [ 1.90061215e+00  1.21817551e+00 -1.07617638e+00 -6.31083099e-01]
 [ 5.82351290e-01 -1.02262000e+00 -4.61674857e-01  1.13054258e+00]
 [ 2.48268021e+00  1.01465451e+00 -1.49662899e+00 -2.23781226e+00]
 [ 3.28214810e-01 -3.34128457e-01 -2.03143044e-01  2.24870601e+00]
 [ 2.21745065e+00  9.79818540e-01 -1.32098998e+00 -1.59432162e+00]
 [ 1.91469190e+00  1.71392114e+00 -1.02375974e+00 -3.22062622e-01]
 [ 1.11822739e+00 -8.08908210e-01 -7.98623068e-01 -6.99905425e-02]
 [ 6.30245062e-01  6.68323722e-01 -2.82797549e-01  2.18491333e+00]]


In [16]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [17]:
a = sigmoid(h)
print(a)

[[0.37484812 0.09922696 0.53313155 0.95529835]
 [0.50078847 0.4936159  0.51400391 0.96378676]
 [0.86996079 0.77174231 0.25423028 0.34726499]
 [0.64160826 0.26451737 0.38658858 0.75593902]
 [0.92291868 0.73393006 0.18292884 0.09640595]
 [0.58132495 0.41723645 0.44938817 0.90453886]
 [0.90180568 0.72707221 0.21065363 0.16877674]
 [0.87154534 0.84734418 0.2642957  0.42017315]
 [0.75365977 0.3081232  0.31032014 0.4825095 ]
 [0.65254503 0.66112771 0.42976805 0.89888652]]


In [18]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))


x =  np.random.randn(10, 2) # 입력 (미니배치, 입력)

W1 = np.random.randn(2,4) # 가중치 1
b1 = np.random.randn(4) # 편향 1

W2 = np.random.randn(4, 3) # 가중치 2
b2 = np.random.randn(3) # 편향 2

h = np.matmul(x, W1) + b1
a = sigmoid(h)
s = np.matmul(a, W2) + b2

print(s)

[[ 0.45630607 -2.5589403  -1.21747914]
 [ 0.3541744  -2.19290512 -0.98885838]
 [ 1.72051088 -2.60299912 -1.43225782]
 [ 1.70333893 -1.96320561 -0.87072307]
 [-0.15328448 -2.04251607 -0.9490962 ]
 [ 0.81785646 -1.84302889 -0.88171362]
 [ 0.39716994 -2.57818712 -1.22796518]
 [ 0.61975368 -2.34011779 -1.08243719]
 [ 0.09804114 -2.36327925 -1.08314429]
 [ 1.88766373 -1.64332234 -0.55257926]]


In [19]:
class Sigmoid:
  def __init__(self):
    self.params = []

  def forward(self, x):
    return 1 / (1+ np.exp(-x))

In [20]:
class Affine:
  def __init__(self, W, b):
    self.params = [W,b]
  
  def forward(self, x):
    W, b = self.params
    out = np.matmul(x,W) + b
    return out

In [21]:
class TwoLayerNet:
  def __init__(self, input_size, hidden_size, output_size):
    I, H, O = input_size, hidden_size, output_size

    W1 = np.random.randn(I, H)
    b1 = np.random.randn(H)
    W2 = np.random.randn(H, O)
    b2 = np.random.randn(O)

    self.layers = [
                  Affine(W1, b1),
                  Sigmoid(),
                  Affine(W2, b2)
                ]

    self.params = []
    for layer in self.layers:
      self.params += layer.params
    
  def predict(self, x):
    for layer in self.layers:
      x = layer.forward(x)
    
    return x

In [22]:
x = np.random.randn(10,2)
model = TwoLayerNet(2,4,3)
model.predict(x)

array([[1.24924928, 1.55330193, 0.60899702],
       [1.0393592 , 1.64470063, 0.72849946],
       [1.3927452 , 1.75774621, 0.91623522],
       [1.0515307 , 1.26419689, 0.22169261],
       [1.35239854, 1.27553881, 0.22020964],
       [1.6509224 , 1.35041942, 0.22070088],
       [1.44180554, 1.77971383, 0.88090693],
       [1.29832055, 1.24550772, 0.19825513],
       [1.44233463, 1.77885579, 0.8663105 ],
       [1.16881752, 1.63579228, 0.73500623]])

### Repeat 노드

In [23]:
D, N = 8, 7
x = np.random.randn(1, D)
y = np.repeat(x, N, axis=0)
print(y)

[[ 0.74401029  0.97301726 -0.47277522 -0.19075705 -1.27445281 -0.68711989
  -0.50869094 -1.49218406]
 [ 0.74401029  0.97301726 -0.47277522 -0.19075705 -1.27445281 -0.68711989
  -0.50869094 -1.49218406]
 [ 0.74401029  0.97301726 -0.47277522 -0.19075705 -1.27445281 -0.68711989
  -0.50869094 -1.49218406]
 [ 0.74401029  0.97301726 -0.47277522 -0.19075705 -1.27445281 -0.68711989
  -0.50869094 -1.49218406]
 [ 0.74401029  0.97301726 -0.47277522 -0.19075705 -1.27445281 -0.68711989
  -0.50869094 -1.49218406]
 [ 0.74401029  0.97301726 -0.47277522 -0.19075705 -1.27445281 -0.68711989
  -0.50869094 -1.49218406]
 [ 0.74401029  0.97301726 -0.47277522 -0.19075705 -1.27445281 -0.68711989
  -0.50869094 -1.49218406]]


In [24]:
dy = np.random.randn(N, D)
dx = np.sum(dy, axis=0, keepdims=True)
print(dx)

[[ 2.12260485 -0.3102795  -4.69479171 -3.76305331  0.71872077  0.2503501
  -2.50045669 -1.20145683]]


### Sum 노드

In [25]:
D, N = 8,7
x = np.random.randn(N,D)
y = np.sum(x, axis=0, keepdims=True)
print(y)

[[ 0.17286953 -0.97925285 -0.44665114 -1.60711152 -2.0684501  -0.5583603
  -4.85525835  0.04516834]]


In [26]:
dy = np.random.randn(1,D)
dx = np.repeat(dy, N, axis=0)
print(dx)

[[-0.48243758  2.05286252 -0.9299429   1.61415261 -0.13809525  0.8203023
   1.39808339  0.48932424]
 [-0.48243758  2.05286252 -0.9299429   1.61415261 -0.13809525  0.8203023
   1.39808339  0.48932424]
 [-0.48243758  2.05286252 -0.9299429   1.61415261 -0.13809525  0.8203023
   1.39808339  0.48932424]
 [-0.48243758  2.05286252 -0.9299429   1.61415261 -0.13809525  0.8203023
   1.39808339  0.48932424]
 [-0.48243758  2.05286252 -0.9299429   1.61415261 -0.13809525  0.8203023
   1.39808339  0.48932424]
 [-0.48243758  2.05286252 -0.9299429   1.61415261 -0.13809525  0.8203023
   1.39808339  0.48932424]
 [-0.48243758  2.05286252 -0.9299429   1.61415261 -0.13809525  0.8203023
   1.39808339  0.48932424]]


### MatMul 노드

In [27]:
class MatMul:
  def __init__(self, W):
    self.params = [W]
    self.grads = [np.zero_like(W)]
    self.x = None
  
  def forward(self, x):
    W, = self.params
    print(self.params)
    out = np.matmul(x,W)
    self.x = x
    return out

  def backward(self, dout):
    W, = self.params
    dx = np.matmul(dout, W.T)
    dW = np.matmul(self.x.T, dout)
    self.grads[0][...] = dW
    return dx

In [28]:
class Sigmoid:
  def __init__(self):
    self.params = []

  def forward(self, x):
    return 1 / (1+ np.exp(-x))

  def backward(self, dout):
    dx = dout * (1.0 - self.out) * self.out
    return dx

In [50]:
class Affine:
  def __init__(self, W, b):
    self.params = [W,b]
    self.grads = [np.zeros_like(W), np.zeros_like(b)]
    self.x = None

  def forward(self, x):
    W,b = self.params
    out = np.matmul(x, W) + b
    return out
  
  def backward(self, dout):
    W,b = self.params
    dx = np.matmul(dout, W.T)
    dW = np.matmul(self.x.T, dout)
    db = np.sum(dout, axis=0)

    self.grads[0][...] = dW
    self.grads[1][...] = db

    return dx

In [82]:
class SGD:
  def __init__(self, lr=0.01):
    self.lr = lr
  
  def update(self, params, grads):
    for i in range(len(params)):
      params[i] -= self.lr * grads[i]

In [83]:
from sample.common.layers import Affine, Sigmoid, SoftmaxWithLoss

In [75]:
class TwoLayerNet:
  def __init__(self, input_size, hidden_size, output_size):
    I, H, O = input_size, hidden_size, output_size

    W1 = 0.01 * np.random.randn(I,H)
    b1 = np.zeros(H)
    
    W2 = 0.01 * np.random.randn(H, O)
    b2 = np.zeros(O)

    self.layers = [
                   Affine(W1,b1),
                   Sigmoid(),
                   Affine(W2,b2)
    ]

    self.loss_layer = SoftmaxWithLoss()

    self.params, self.grads = [], []
    for layer in self.layers:
      self.params += layer.params
      self.grads += layer.grads

  def predict(self, x):
    for layer in self.layers:
      x = layer.forward(x)
    return x
  
  def forward(self, x, t):
    score = self.predict(x)
    loss = self.loss_layer.forward(score, t)
    return loss
  
  def backward(self, dout=1):
    dout = self.loss_layer.backward(dout)
    for layer in reversed(self.layers):
      dout = layer.backward(dout)
    return dout
      

### 학습용 코드

In [76]:
from sample.dataset_py import spiral

In [77]:
epochs = 300
batch_size = 30
hidden_size = 10
learning_rate = 1.0

In [84]:
x, t = spiral.load_data()
model = TwoLayerNet(input_size=2, hidden_size=hidden_size, output_size=3)
optimizer = SGD(lr=learning_rate)

In [85]:
data_size = len(x)
max_iters = data_size//batch_size
total_loss = 0
total_count =0
loss_list = []

In [86]:
for epoch in range(epochs):
  idx = np.random.permutation(data_size)
  x = x[idx]
  t = t[idx]

  for iters in range(max_iters):
    batch_x = x[iters*batch_size:(iters+1)*batch_size]
    batch_t = t[iters*batch_size:(iters+1)*batch_size]

    loss = model.forward(batch_x, batch_t)
    model.backward()
    optimizer.update(model.params, model.grads)

    total_loss +=loss
    loss_count = 1

    if (iters+1) % 10 == 0:
      avg_loss = total_loss / loss_count
      print("| 에폿 %d | 반복 %d / %d | 손실 %.2f"%(epoch+1, iters+1, max_iters, avg_loss))
      loss_list.append(avg_loss)
      total_loss, loss_count = 0, 0

| 에폿 1 | 반복 10 / 10 | 손실 11.26
| 에폿 2 | 반복 10 / 10 | 손실 11.26
| 에폿 3 | 반복 10 / 10 | 손실 11.16
| 에폿 4 | 반복 10 / 10 | 손실 11.16
| 에폿 5 | 반복 10 / 10 | 손실 11.12
| 에폿 6 | 반복 10 / 10 | 손실 11.38
| 에폿 7 | 반복 10 / 10 | 손실 11.59
| 에폿 8 | 반복 10 / 10 | 손실 11.09
| 에폿 9 | 반복 10 / 10 | 손실 11.17
| 에폿 10 | 반복 10 / 10 | 손실 11.29
| 에폿 11 | 반복 10 / 10 | 손실 11.17
| 에폿 12 | 반복 10 / 10 | 손실 11.08
| 에폿 13 | 반복 10 / 10 | 손실 10.88
| 에폿 14 | 반복 10 / 10 | 손실 10.77
| 에폿 15 | 반복 10 / 10 | 손실 10.44
| 에폿 16 | 반복 10 / 10 | 손실 10.35
| 에폿 17 | 반복 10 / 10 | 손실 9.57
| 에폿 18 | 반복 10 / 10 | 손실 9.18
| 에폿 19 | 반복 10 / 10 | 손실 9.24
| 에폿 20 | 반복 10 / 10 | 손실 8.69
| 에폿 21 | 반복 10 / 10 | 손실 8.49
| 에폿 22 | 반복 10 / 10 | 손실 8.17
| 에폿 23 | 반복 10 / 10 | 손실 7.92
| 에폿 24 | 반복 10 / 10 | 손실 7.83
| 에폿 25 | 반복 10 / 10 | 손실 8.24
| 에폿 26 | 반복 10 / 10 | 손실 7.75
| 에폿 27 | 반복 10 / 10 | 손실 7.56
| 에폿 28 | 반복 10 / 10 | 손실 7.64
| 에폿 29 | 반복 10 / 10 | 손실 7.83
| 에폿 30 | 반복 10 / 10 | 손실 7.51
| 에폿 31 | 반복 10 / 10 | 손실 7.77
| 에폿 32 | 반복 10 / 10 | 손실 7.65
|

In [87]:
np.random.permutation(10)

array([5, 1, 8, 4, 9, 7, 0, 2, 6, 3])